# .github/workflows/manual_crossplatform_build.yml
name: Manual Cross-platform Build Shotgun Code

on:
  workflow_dispatch:

env:
  NODE_OPTIONS: "--max-old-space-size=4096"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          # Linux
          - os: ubuntu-latest
            platform: linux/amd64
            name: shotgun-code
            safe: linux-amd64
            ext: ""
          - os: ubuntu-latest
            platform: linux/arm64
            name: shotgun-code
            safe: linux-arm64
            ext: ""
          # Windows
          - os: windows-latest
            platform: windows/amd64
            name: shotgun-code
            safe: windows-amd64
            ext: ".exe"
          - os: windows-latest
            platform: windows/arm64
            name: shotgun-code
            safe: windows-arm64
            ext: ".exe"
          # macOS
          - os: macos-latest
            platform: darwin/amd64
            name: shotgun-code
            safe: darwin-amd64
            ext: ""
          - os: macos-latest
            platform: darwin/arm64
            name: shotgun-code
            safe: darwin-arm64
            ext: ""
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
          submodules: recursive

      - name: Build Wails app (${{ matrix.platform }})
        uses: dAppServer/wails-build-action@main
        with:
          build-name: ${{ matrix.name }}-${{ matrix.safe }}${{ matrix.ext }}
          build-platform: ${{ matrix.platform }}
          package: true
          go-version: '1.24'

      - name: Zip macOS app
        if: matrix.os == 'macos-latest'
        run: |
          APP_PATH=$(ls build/bin/*.app | head -n1)
          ZIP_PATH=${APP_PATH}.zip
          echo "Zipping $APP_PATH → $ZIP_PATH"
          ditto -c -k --keepParent "$APP_PATH" "$ZIP_PATH"

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: shotgun_code-${{ matrix.safe }}
          path: build/bin/