# .github/workflows/manual_crossplatform_build.yml
name: Manual Cross-platform Build Shotgun Code

on:
  workflow_dispatch:   # enable the “Run workflow” button

env:
  NODE_OPTIONS: "--max-old-space-size=4096"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux/amd64
          - os: windows-latest
            platform: windows/amd64
          - os: macos-latest
            platform: darwin/amd64   # darwin/universal can sometimes mis-resolve – darwin/amd64 is safest
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Install Wails CLI
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install frontend dependencies
        run: npm ci
        working-directory: ./frontend

      - name: Build frontend
        run: npm run build
        working-directory: ./frontend

      - name: Build Wails app (${{ matrix.platform }})
        run: wails build --platform ${{ matrix.platform }}

      - name: Upload binaries
        uses: actions/upload-artifact@v3
        with:
          name: shotgun_code-${{ matrix.platform }}
          path: build/bin/