# .github/workflows/manual_crossplatform_build.yml
name: Manual Cross‐platform Build Shotgun Code

on:
  workflow_dispatch:              # позволяет запускать вручную из UI

env:
  NODE_OPTIONS: "--max-old-space-size=4096"  # чтобы избежать OOM при сборке фронтенда

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux/amd64
          - os: windows-latest
            platform: windows/amd64
          - os: macos-latest
            platform: darwin/universal
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Install Wails CLI
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Build frontend
        working-directory: ./frontend
        run: npm run build

      - name: Build Wails app (${{ matrix.platform }})
        run: wails build --platform ${{ matrix.platform }}

      - name: Upload binaries
        uses: actions/upload-artifact@v3
        with:
          name: shotgun_code-${{ matrix.platform }}
          path: build/bin/
