# .github/workflows/manual_crossplatform_build.yml
name: Manual Cross-platform Build Shotgun Code

on:
  workflow_dispatch:   # enable the "Run workflow" button

env:
  NODE_OPTIONS: "--max-old-space-size=4096"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux_amd64
            name: 'shotgun-code'
          - os: windows-latest
            platform: windows_amd64
            name: 'shotgun-code'
          - os: macos-latest
            platform: darwin_universal
            name: 'shotgun-code'
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
          submodules: recursive

      - name: Build Wails app (${{ matrix.platform }})
        uses: dAppServer/wails-build-action@main
        id: wails_build
        with:
          build-name: ${{ matrix.name }}
          build-platform: ${{ matrix.platform }}
          package: false
          go-version: '1.24'

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: shotgun_code-${{ matrix.platform }}
          path: build/bin/