name: Manual Cross-platform Build Shotgun Code

on:
  workflow_dispatch:

env:
  NODE_OPTIONS: "--max-old-space-size=4096"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          # ───────────── Linux ─────────────
          - os: ubuntu-latest
            platform: linux/amd64
            build_name: shotgun-code-linux-amd64
            artifact_name: shotgun_code-linux-amd64

          # ──────────── Windows ────────────
          - os: windows-latest
            platform: windows/amd64
            build_name: shotgun-code-windows-amd64.exe
            artifact_name: shotgun_code-windows-amd64


          # ───────────── macOS ─────────────
          #  Имя .app = «shotgun-code», без суффикса!
          - os: macos-latest
            platform: darwin/amd64
            build_name: shotgun-code
            artifact_name: shotgun_code-darwin-amd64

          - os: macos-latest
            platform: darwin/arm64
            build_name: shotgun-code
            artifact_name: shotgun_code-darwin-arm64

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
          submodules: recursive

      - name: Build Wails app (${{ matrix.platform }})
        uses: dAppServer/wails-build-action@main   # v3/current main
        with:
          build-name: ${{ matrix.build_name }}
          build-platform: ${{ matrix.platform }}
          go-version: '1.24'
          package: true            # action сам zip‑ует и загружает .app

      # Дополнительный ditto не нужен — action уже упаковал Mac‑сборку.

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: build/bin/
